[workspace]

members = [
    "near-signers",
    "near-providers",
    "near-transactions",
    "near-api",
    "near-keystores",
    "near-accounts"
]

exclude = ["examples/"]

[workspace.package]
version = "0.0.1"